version: '3'
services:
  chat-backend:
    build:
      context: ./backend
    links:
      - chat-redis
    ports:
      - 5001:80
    environment:
      - REDIS_CONNECTIONSTRING=192.168.14.39:6379
  
  chat-frontend:
    build:
      context: ./frontend
    links:
      - chat-backend
    ports:
      - 4001:80

  chat-redis:
    image: redis
    ports:
      - 6379:6379